### ISSUE TITLE
Cannot update to 2.0.1

### ISSUE THREAD

**Issue by 15cm** [akfish/hexo-math#11]
I want to update from 1.0.6 to 2.0.1. However, after running

    npm install hexo-math --save

Then I find version of hexo-math is 1.0.8 and the tag `{% math %} ... {% endmath %}` cannot be recognized.
Although tag `{% math } ... { %}` still work for me and my site is alright, I still wonder why I can't update to the latest version.
Thanks!

**Comment by akfish** [comment]
Run:
> npm install hexo-math@latest --save

or 

> npm install hexo-math@2.0.1 --save

`npm` will install the version specified in `package.json` (which is set in your previous installation), if no version number is provided.
