### ISSUE TITLE
This formula can't be displayed correctly.

### ISSUE THREAD

**Issue by wangck1998** [akfish/hexo-math#13]
```
$$F(n)=\sum_{n|d}f(d) \Rightarrow f(n)=\sum_{d} \mu ({d\over n}) F(d)$$
```

This formula can't be displayed correctly.

But the formula below is OK.

```
$$F(n)=\sum_{n|d}f(d) \Rightarrow f(n)=\sum_d \mu ({d\over n}) F(d)$$
```

**Comment by wangck1998** [comment]
```
<p>$$F(n)=\sum<em>{n|d}f(d) \Rightarrow f(n)=\sum</em>{d} \mu ({d\over n}) F(d)$$</p>
```

**Comment by akfish** [comment]
This behavior is by design in current version. Try using `{% math %}...{% endmath %}` tag, which does not require manually escaping special characters. 
I'll add auto-escape feature in future versions. Close for now.
