### ISSUE TITLE
如何给公式编号

### ISSUE THREAD

**Issue by modkzs** [akfish/hexo-math#14]
mathjax中的\label{id}似乎并不支持

**Comment by akfish** [comment]
Fixed in 2.1.0

**Comment by modkzs** [comment]
升级到2.1.0但是看网页源代码并没有看到mathjax中有equationNumbers的配置

**Comment by modkzs** [comment]
升级到2.1.0但是没有看到网页源代码中出现对equationNumbers的配置js代码。@akfish

**Comment by akfish** [comment]
如果是注入的配置不正确，检查或者删除`_config.yml`中的`mathjax`配置，[默认配置](https://github.com/akfish/hexo-math#config)已加入公式编号支持。

如果完全没有MathJax的script被注入（包括对MathJax的引用），检查你的hexo版本是否是3.2.0，renderer是否是最新版。Hexo 3.2.0模板预编译引入的bug会导致脚本不能正确注入，把renderer降级到之前不支持预编译的版本可修复这个问题。

hexojs/hexo#1791
