### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by happynear** [akfish/hexo-math#23]
I installed hexo-math yesterday, but none math fomula is rendered. Is it because your under construction project hexo-inject? How can I find an old version?

**Comment by happynear** [comment]
Now I can successfully load some of simple formulations, but many complex ones still cannot be loaded.

My post is in http://saban.wang/2016/03/21/Normalization-Propagation/ . Note that I use CMD markdown to edit my blog. It also uses the Mathjax, so I don't think it is a Mathjax problem.

**Comment by happynear** [comment]
I have fixed it. I need to manually replace the <em> and <br> tags in the formulations. It is boring but works. I hope someone could fix it.

**Comment by happynear** [comment]
I found the [Next theme](https://github.com/iissnan/hexo-theme-next) has already integrated the MathJax engine. I unistalled hexo-math temporarily. If you have solved the \<em\> problem, please kindly tell me.

**Comment by akfish** [comment]
Were you using inline/block math or `{% math %} tag?

**Comment by happynear** [comment]
I am using $$.
I have fixed it now by using pandoc to render the markdown. Pandoc can preserve the format between $$s.

**Comment by akfish** [comment]
Thanks for the clarification. It's expected that some Markdown engines (like Hexo's default one) would mess $$ expressions up. `$a*b*c$` will be rendered into $a*b*c$ (`$a<em>b</em>c$`). Aside from changing the Markdown engine, using `{% math %}` would solve the problem too.
