### ISSUE TITLE
Katex 引擎只能渲染 {% math %} {% endmath %} 中的公式是正常的吗？

### ISSUE THREAD

**Issue by azone** [akfish/hexo-math#24]
Katex 引擎只能渲染 `{% math %}xxx{% math_end %}` 中的公式不能渲染 `$$xxx$$` 或者 `$xxx$` 是正常的吗？如图：

源码： 
<img width="808" alt="2016-03-24 2 19 19" src="https://cloud.githubusercontent.com/assets/164407/14009931/83cb1178-f1cb-11e5-8148-b8c0c6a96a3a.png">
渲染后： 
<img width="375" alt="2016-03-24 2 19 35" src="https://cloud.githubusercontent.com/assets/164407/14009934/8853f3d6-f1cb-11e5-9ed3-acfb1e238b7c.png">

**Comment by akfish** [comment]
是的，README里有说明。

**Comment by azone** [comment]
谢谢~
