### ISSUE TITLE
为什么要注释掉这一行呢？

### ISSUE THREAD

**Issue by intijk** [akfish/hexo-math#27]
// post.register();

有这个功能挺好啊，可以在markdown之前解析，为什么在代码里关了呢？会导致冲突吗？

能不能给个选项让我打开它？

**Comment by akfish** [comment]
目前的实现是简单替换`$...$`或`$$...$$`之间的内容，如果在不同的Markdown node中出现了`$`或者`$$`，就会造成错误的解析结果。

比如：
```markdown
`code span $1` and `code span $2`
```

```markdown
# Give me $$

# Give me more $$
```

另据[CommonMark Spec](http://spec.commonmark.org/0.25/)，部分node（如HTML block，code block）应当保持原有文本，不应进行渲染。

正确的实现需要使用Markdown parser，根据node类型渲染，后续版本也许会采用这一实现。
