### ISSUE TITLE
Resize problem

### ISSUE THREAD

**Issue by Response777** [akfish/hexo-math#32]
It seems that the formula cannot resize responsively.
So when view with mobile device, the formula may be so wide that it stretch outside the box.

**Comment by akfish** [comment]
Responsiveness should be implemented by the rendering engine, not this plugin. Neither MathJax nor KaTeX handles it well.
Try activating line-breaking for MathJax. [\[1\]][1][\[2\]][2]
Try waiting for this feature to be added for KaTeX. Khan/KaTeX#327

[1]: http://stackoverflow.com/questions/29893923/how-to-make-formula-with-mathjax-responsive
[2]: http://docs.mathjax.org/en/latest/output.html#automatic-line-breaking

**Comment by Response777** [comment]
Thanks. However, I have solved this problem to some degree.
You can try _cross validation_ or _Math Stackexchange_, and you'll find that they resize the formula according to page's size.

With the help of certain material(List below), I have tried on my github.io and it proves to work smoothly. But I wonder if it can be solved with pure css.

btw: Since I'm not familiar with front-end, I doubt this implement may influence the performance. But as far as I'm concerned, the complexity of this method should be accepted(It holds from the premise that the size of Mathjax formula is finally decided after the construction of the DOM tree.) 

Ref: [http://www.math.union.edu/~dpvc/talks/2013-01-12.jmm/sample8-src.html](url)

**Comment by akfish** [comment]
I'm glad you find a solution. It seems to be a good one. Thanks for sharing.
Messing with CSS could potentially break user's theme or other plugins. It should be done in a controlled manner by the user for his specific setup. So it will not be implemented it in the plugin.
