### ISSUE TITLE
Adding a per-post/per-page setting to enable MathJax

### ISSUE THREAD

**Issue by Hunter-Github** [akfish/hexo-math#6]
When some posts do not use math, it would be sensible to leave out heavy MathJax plugin. A post-level variable `mathjax` would be fine. Of course, if one displayed post out of ten uses MathJax, the whole index page would load it too.

**Comment by akfish** [comment]
I've been investigating the possibility of loading MathJax on demand automatically in the next version. It should do exactly what you are suggesting without the need for manual configuration.

**Comment by Hunter-Github** [comment]
Thanks a bunch, that would be great!

**Comment by akfish** [comment]
Implemented in 1.0.6.
