### ISSUE TITLE
Strange rendering of math inlines in a bullet list

### ISSUE THREAD

**Issue by Hunter-Github** [akfish/hexo-math#7]
Source:

     * {% math \sigma_i %} -something
     * {% math \sigma_i %} -something
     * {% math \sigma_i %} -something

Renders like

* * CORRECTLY RENDERED MATH  - something
* * CORRECTLY RENDERED MATH  - something
* * CORRECTLY RENDERED MATH  - something

This is under hexo-math 1.0.6, and hexo 3.1.1.

**TL;DR** - an extra asterisk is inserted somewhere.

**Comment by akfish** [comment]
Multiple versions have been published since this issue. The bug reported here was fixed somewhere along the way. 
Note that the syntax used in this issue is no longer valid due to fixes made for #9. See [Migrating to 2.0.0](https://github.com/akfish/hexo-math#migrating-to-200).
