### ISSUE TITLE
自動注入失敗

### ISSUE THREAD

**Issue by morris821028** [akfish/hexo-math#8]
```
Simple inline $a = b + c$.
```

如果文章只有上述的操作，會造成注入 mathjax 失敗，一定要出現 `{% math %}` 或者 `{% math_block %}` 才會生效。

在自動偵測部分，https://github.com/akfish/hexo-math/blob/master/bin/index.js#L46 是不是要改成
```
hasMath = src.indexOf("<!-- Has MathJax -->") >= 0 || src.indexOf("$") >= 0;
```

**Comment by akfish** [comment]
Published as 1.0.8 and 2.0.0 (including breaking changes introduced due to #9)
