### ISSUE TITLE
Hexo 3.x Tag Engine Nunjucks instead of Swig

### ISSUE THREAD

**Issue by morris821028** [akfish/hexo-math#9]
Nunjucks 在 `{% extends args %}` 的解析不同於 Swig，導致 args 出現 `{{` 或者 `}}` 的發生問題。

例如在 Hexo 2.x 版本，`{% math \frac{|ax + by + c|}{\sqrt{a^{2}+b^{2}}} %}` 是不會有問題，但在 Hexo 3.x 會發生錯誤，要強制消除掉 `{{` 和 `}}` 的出現。

對於 inline 版本，是否要更改成使用上下對應的方式，還是有其他解決方法。
```
{% math %}\frac{|ax + by + c|}{\sqrt{a^{2}+b^{2}}} {% endmath %}
```
關聯的部分：
```
hexo.extend.tag.register("math", function(args, content) {
  var result;
  result = "<span>$" + content + "$</span><!-- Has MathJax -->";
  return result;
}, {
  ends: true
});
```

**Comment by akfish** [comment]
Published as 2.0.0
